name: Test
description: テストの追加・改善
title: "[Test] "
labels: ["test"]

body:
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      default: 3
      options:
        - 高
        - 中
        - 低
        - 未定
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 対象となるテストの内容を簡潔に記載してください
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景
      description: なぜこのテストが必要なのかを記載してください
    validations:
      required: true

  - type: textarea
    id: flow
    attributes:
      label: 実装フロー
      value: |
        - [ ]
        - [ ]
        - [ ]

  - type: textarea
    id: done
    attributes:
      label: 完了条件
      value: |
        - [ ] テストケースを満たしている
        - [ ] テストが通過している
        - [ ] レビューが完了している
    validations:
      required: true
